version: '3'
services:
  api:
    build: ./springboot-api-docker
    ports:
      - "9090:9090"
    depends_on:
      - database
  client:
    build: ./springboot-client-docker
    ports:
      - "8080:8080"
    depends_on:
      - api
  database:
    container_name: 'mysql'
    image: mysql
    restart: always
    environment:
      MYSQL_PASSWORD:
      MYSQL_USER: user
      MYSQL_DATABSE: test
    ports:
      - "3036:3036"

